const actionTypes = {

  // user
  ADD_USER: 'ADD_USER',
  // UPD_USER: 'UPD_USER',
  UPD_USER_NAME: 'UPD_USER_NAME',
  LOAD_USER: 'LOAD_USER',

  // travel
  ADD_TRAVEL: 'ADD_TRAVEL',
  UPD_TRAVEL_TITLE: 'UPD_TRAVEL_TITLE',
  UPD_TRAVEL_DATE: 'UPD_TRAVEL_DATE',
  UPD_ACCOUNTING_LIST: 'UPD_ACCOUNTING_LIST',
  LOAD_TRAVEL: 'LOAD_TRAVEL',

  // accounting
  ADD_ACCOUNTING: 'ADD_ACCOUNTING',
  UPD_ACCOUNTING_TITLE: 'UPD_ACCOUNTING_TITLE',
  UPD_ACCOUNTING_DATE: 'UPD_ACCOUNTING_DATE',
  UPD_ACCOUNTING_PAYMENT: 'UPD_ACCOUNTING_PAYMENT',
  UPD_ACCOUNTING_CREDIT: 'UPD_ACCOUNTING_CREDIT',
  UPD_ACCOUNTING_AMOUNT: 'UPD_ACCOUNTING_AMOUNT',
  LOAD_ACCOUNTING: 'LOAD_ACCOUNTING',
}

export default actionTypes;
